export const authStore = {
  token: "K99heh8grje1TJYk5KCcjUEuSPteC281Dx9XTMut8vM",
  userInfo: {
    acct: "all_about_anime",
    avatar:
      "https://s3-eu-west-2.amazonaws.com/patchwork-prod/accounts/avatars/113/690/159/050/828/050/original/image.jpg",
    avatar_static:
      "https://s3-eu-west-2.amazonaws.com/patchwork-prod/accounts/avatars/113/690/159/050/828/050/original/image.jpg",
    bot: true,
    created_at: "2024-12-21T00:00:00.000Z",
    discoverable: true,
    display_name: "All About Anime",
    emojis: [],
    fields: [[]],
    followers_count: 28,
    following_count: 17,
    group: false,
    header: "https://channel.org/headers/original/missing.png",
    header_static: "https://channel.org/headers/original/missing.png",
    hide_collections: null,
    id: "113690159050828050",
    indexable: false,
    last_status_at: "2025-03-11",
    locked: false,
    noindex: false,
    note: "<p>Bot Account For Boosting Anime Related News 24/7</p>",
    role: {
      color: "",
      highlighted: false,
      id: "6",
      name: "UserAdmin",
      permissions: "65536",
    },
    roles: [],
    source: {
      attribution_domains: [],
      discoverable: true,
      email: "yemyatthu.cs@gmail.com",
      fields: [],
      follow_requests_count: 0,
      hide_collections: null,
      indexable: false,
      language: null,
      note: "Bot Account For Boosting Anime Related News 24/7",
      privacy: "public",
      sensitive: false,
    },
    statuses_count: 1649,
    uri: "https://channel.org/users/all_about_anime",
    url: "https://channel.org/@all_about_anime",
    username: "all_about_anime",
  },
  userOriginInstance: "https://channel.org",
};
